# Azure App Service Configuration
# This file configures the deployment and runtime settings

# Build configuration
build:
  # Build commands
  commands:
    - npm ci
    - npm run build
  
  # Build artifacts
  artifacts:
    - .next/
    - public/
    - package.json
    - next.config.ts
    - tsconfig.json

# Runtime configuration
runtime:
  # Node.js version
  nodeVersion: "22.15.0"
  
  # Start command
  startCommand: "cd /home/site/wwwroot && npm install --omit=dev && npm run build && npm start"
  
  # Environment variables
  environment:
    NODE_ENV: "production"
    NEXT_TELEMETRY_DISABLED: "1"
    WEBSITE_NODE_DEFAULT_VERSION: "22.15.0"
    SCM_DO_BUILD_DURING_DEPLOYMENT: "true"
    BUILD_FLAGS: "--platform nodejs --platform-version 22.15.0"
    WEBSITES_PORT: "8080"

# Deployment settings
deployment:
  # Deployment method
  method: "zip"
  
  # Include files
  include:
    - "**/*"
  
  # Exclude files
  exclude:
    - "node_modules/**"
    - ".git/**"
    - "*.log"
    - "coverage/**"
    - ".env*"
    - ".next/cache/**"
    - "deployment.zip" 